DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dyeti') THEN
CREATE ROLE dyeti WITH LOGIN SUPERUSER PASSWORD 'dyeti_pass';
ELSE
    ALTER ROLE dyeti WITH LOGIN SUPERUSER PASSWORD 'dyeti_pass';
END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE dyeti_db TO dyeti;
