FROM gradle:8.13-jdk21
WORKDIR /app

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
RUN ./gradlew dependencies --no-daemon

ENV SPRING_PROFILES_ACTIVE=dev
ENV JAVA_TOOL_OPTIONS="-Dspring.devtools.restart.enabled=true"

CMD ["./gradlew", "bootRun", "--continuous", "--no-daemon"]
