FROM gradle:8.13-jdk21
WORKDIR /app

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
RUN ./gradlew dependencies --no-daemon

ENV SPRING_PROFILES_ACTIVE=dev

CMD ["./gradlew", "bootRun", "--no-daemon"]
