spring.application.name=dyeti-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dyeti_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dyeti
spring.datasource.password=dyeti_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
