name: Deploy on VM Norymberga

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  push:
    branches:
      - develop
      - feature/CD-workflow

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          host="$(echo "${{ secrets.VM_ADDRESS }}" | awk -F'@' '{print $2}')"
          ssh-keyscan -H "$host" >> ~/.ssh/known_hosts

      - name: Connect (password)
        env:
          SSHPASS: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -e ssh \
            -o StrictHostKeyChecking=no \
            "${{ secrets.VM_ADDRESS }}" \
            "echo yes"
      - name: Create ENV
        env:
          SSHPASS: ${{ secrets.VM_PASSWORD }}
          VM_ENV: ${{ secrets.VM_ENV }}
        run: |
          printf '%s' "$VM_ENV" | sshpass -e ssh \
            -o StrictHostKeyChecking=no \
            "${{ secrets.VM_ADDRESS }}" \
            'cd test && cat > .env'

      - name: Test on VM (password)
        env:
          SSHPASS: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -e ssh \
            -o StrictHostKeyChecking=no \
            "${{ secrets.VM_ADDRESS }}" \
            "ls -la" 
            
          
